export const categories = [
  { "name": "Acid House" }, { "name": "Acid Jazz" }, { "name": "Acid Rock" }, { "name": "Afro House" }, { "name": "Afro-Cuban" }, { "name": "Afrobeats" }, { "name": "Afropop" }, { "name": "Alcoholic" }, { "name": "Alone" }, { "name": "Alt Pop" }, { "name": "Alt Rock" }, { "name": "Alternative Rock" }, { "name": "Amapiano" }, { "name": "Ambient" }, { "name": "Americana" }, { "name": "Anime OST" }, { "name": "Arabic" }, { "name": "Art Rock" }, { "name": "Asian Traditional" }, { "name": "Assamese" },
  { "name": "Bachata" }, { "name": "Ballad" }, { "name": "Baroque" }, { "name": "Bass music" }, { "name": "Bebop" }, { "name": "Bedroom Pop" }, { "name": "Bengali" }, { "name": "Bhangra" }, { "name": "Bhojpuri" }, { "name": "Big Band" }, { "name": "Big Room" }, { "name": "Black Metal" }, { "name": "Blackgaze" }, { "name": "Blue-eyed Soul" }, { "name": "Bluegrass" }, { "name": "Blues Rock" }, { "name": "Bollywood" }, { "name": "Boom Bap" }, { "name": "Bossa Nova" }, { "name": "Bounce" },
  { "name": "Boy Groups" }, { "name": "Brazilian Jazz" }, { "name": "Breakbeat" }, { "name": "Breakcore" }, { "name": "Breakup" }, { "name": "Brostep" }, { "name": "Celtic" }, { "name": "Chamber Music" }, { "name": "Chanson" }, { "name": "Chicago Blues" }, { "name": "Chicago Drill" }, { "name": "Chill" }, { "name": "Chillhop" }, { "name": "Chillout" }, { "name": "Chillstep" }, { "name": "Chillwave" }, { "name": "Christian Rock" }, { "name": "Tech House" }, { "name": "Techno" }, { "name": "Teen Pop" },
  { "name": "Cinematic" }, { "name": "Classic Country" }, { "name": "Classic Disco" }, { "name": "Classic Hard Rock" }, { "name": "Classic R&B" }, { "name": "Classic Rock" }, { "name": "Classic Soul" }, { "name": "Classical Crossover" }, { "name": "Classical Fusion" }, { "name": "Cloud Rap" }, { "name": "Club" }, { "name": "Conscious Hip Hop" }, { "name": "Conscious Rap" }, { "name": "Contemporary Classical" }, { "name": "Contemporary Gospel" }, { "name": "Contemporary R&B" }, { "name": "Cool Jazz" }, { "name": "Country Pop" }, { "name": "Country Rock" }, { "name": "Crunk" }, { "name": "Crunkcore" },
  { "name": "Cultural" }, { "name": "Cumbia" }, { "name": "Dance" }, { "name": "Dance Pop" }, { "name": "Dancehall" }, { "name": "Darksynth" }, { "name": "Death Metal" }, { "name": "Deep House" }, { "name": "Delta Blues" }, { "name": "Detroit Techno" }, { "name": "Disco" }, { "name": "Disco Funk" }, { "name": "Doom Metal" }, { "name": "Downtempo" }, { "name": "Dream Pop" }, { "name": "Drill" }, { "name": "Drone" }, { "name": "Drum and Bass" }, { "name": "Dub" }, { "name": "Dub Techno" }, { "name": "Dubstep" }, { "name": "Emo" },
  { "name": "Emo Rap" }, { "name": "English" }, { "name": "Epic Music" }, { "name": "Eurodance" }, { "name": "Europop" }, { "name": "Experimental" }, { "name": "Festival Trap" }, { "name": "Film Score" }, { "name": "Folk Metal" }, { "name": "Folk Rock" }, { "name": "Footwork" }, { "name": "French Pop" }, { "name": "Funk" }, { "name": "Funk Rock" }, { "name": "Funk Soul" }, { "name": "Funk-Disco" }, { "name": "Future Bass" }, { "name": "Future Funk" }, { "name": "Future Garage" }, { "name": "Future House" }, { "name": "Fusion" },
  { "name": "Game Soundtrack" }, { "name": "Gangsta Rap" }, { "name": "Garage Grime" }, { "name": "Garage Punk" }, { "name": "Garage Rock" }, { "name": "Ghazal" }, { "name": "Girl Groups" }, { "name": "Glam Rock" }, { "name": "Glitch" }, { "name": "Glitch Hop" }, { "name": "Gothic Metal" }, { "name": "Gothic Rock" }, { "name": "Grunge" }, { "name": "Gujarati" }, { "name": "Gypsy Jazz" }, { "name": "Hardcore Punk" }, { "name": "Hardcore Techno" }, { "name": "Hard Bop" }, { "name": "Hard Rock" }, { "name": "Hard Trap" }, { "name": "Hardstyle" }, { "name": "Haryanvi" },
  { "name": "Heavy Metal" }, { "name": "Heavy Rock" }, { "name": "Highlife" }, { "name": "Hindi" }, { "name": "Hip House" }, { "name": "Honky Tonk" }, { "name": "House" }, { "name": "Hyphy" }, { "name": "IDM" }, { "name": "Indian Classical" }, { "name": "Indie Alternative" }, { "name": "Indie Folk" }, { "name": "Indie Pop" }, { "name": "Indie Rock" }, { "name": "Industrial" }, { "name": "Industrial Metal" }, { "name": "Instrumental Hip Hop" }, { "name": "Italo Disco" }, { "name": "Item Songs" }, { "name": "J-Pop" }, { "name": "J-Rock" }, { "name": "Jazz Fusion" },
  { "name": "Jazz Hop" }, { "name": "Jazz Rap" }, { "name": "Jersey Club" }, { "name": "Jungle" }, { "name": "K-Pop" }, { "name": "K-Rock" }, { "name": "Kannada" }, { "name": "Kashmiri" }, { "name": "Kawaii Metal" }, { "name": "Krautrock" }, { "name": "Latin Jazz" }, { "name": "Latin Pop" }, { "name": "Latin Rock" }, { "name": "Latin Trap" }, { "name": "Lo-fi" }, { "name": "Lo-fi Chill" }, { "name": "Lo-fi Hip-Hop" }, { "name": "Lo-fi Instrumental" }, { "name": "Lo-fi Jazz" }, { "name": "Love" }, { "name": "Lounge" }, { "name": "Malayalam" }, { "name": "Mambo" }, { "name": "Marathi" }, { "name": "Mashup" },
  { "name": "Math Rock" }, { "name": "Meditation" }, { "name": "Melodic Dubstep" }, { "name": "Melodic House" }, { "name": "Melodic Metal" }, { "name": "Melodic Techno" }, { "name": "Melodic Trap" }, { "name": "Memphis Rap" }, { "name": "Merengue" }, { "name": "Metal" }, { "name": "Metalcore" }, { "name": "Microhouse" }, { "name": "Minimal Techno" }, { "name": "Minimalist" }, { "name": "Modern" }, { "name": "Modern Folk" }, { "name": "Moombahton" }, { "name": "Naija" }, { "name": "Neo-Soul" }, { "name": "Neoclassical" }, { "name": "New Age" }, { "name": "New Jack Swing" },
  { "name": "New Wave" }, { "name": "Noise Rock" }, { "name": "Nordic Folk" }, { "name": "Nu Metal" }, { "name": "Nu-Disco" }, { "name": "Nu-Jazz" }, { "name": "Old" }, { "name": "Old School" }, { "name": "Opera" }, { "name": "Orchestral" }, { "name": "Outlaw Country" }, { "name": "Outrun" }, { "name": "P-Funk" }, { "name": "Phonk" }, { "name": "Piano Jazz" }, { "name": "Pop" }, { "name": "Pop Punk" }, { "name": "Pop Rock" }, { "name": "Post Hardcore" }, { "name": "Post-Rock" }, { "name": "Power Metal" }, { "name": "Progressive House" }, { "name": "Progressive Metal" }, { "name": "Progressive Rock" },
  { "name": "Progressive Trance" }, { "name": "Psychedelic Pop" }, { "name": "Psychedelic Rock" }, { "name": "Psytrance" }, { "name": "Punjabi" }, { "name": "Qawwali" }, { "name": "R&B" }, { "name": "Ragga" }, { "name": "Rajasthani" }, { "name": "Rap Metal" }, { "name": "Reggae" }, { "name": "Reggae Fusion" }, { "name": "Reggaeton" }, { "name": "Retro" }, { "name": "Retrowave" }, { "name": "Riddim" }, { "name": "Road Rap" }, { "name": "Rock Opera" }, { "name": "Rockabilly" }, { "name": "Romantic" }, { "name": "Roots Reggae" }, { "name": "Sad" }, { "name": "Salsa" }, { "name": "Shoegaze" },
  { "name": "Ska" }, { "name": "Ska Punk" }, { "name": "Slowed" }, { "name": "Smooth Jazz" }, { "name": "Soca" }, { "name": "Soft Loffy" }, { "name": "Soft night" }, { "name": "Soft Rock" }, { "name": "Solo" }, { "name": "Soul" }, { "name": "Soundscape" }, { "name": "Speed Metal" }, { "name": "Stoner Rock" }, { "name": "String Quartet" }, { "name": "Study Beats" }, { "name": "Sufi" }, { "name": "Surf Rock" }, { "name": "Swing" }, { "name": "Symphony" }, { "name": "Synth Pop" }, { "name": "Synthwave" }, { "name": "Tamil" }, { "name": "Tango" },
  { "name": "Telugu" }, { "name": "Thrash Metal" }, { "name": "Thumri" }, { "name": "Traditional" }, { "name": "Traditional Folk" }, { "name": "Traditional Gospel" }, { "name": "Trance" }, { "name": "Trap" }, { "name": "Trap Metal" }, { "name": "Trap Soul" }, { "name": "Trip Hop" }, { "name": "Tropical House" }, { "name": "TV Soundtrack" }, { "name": "UK Drill" }, { "name": "UK Garage" }, { "name": "UK Grime" }, { "name": "Underground" }, { "name": "Uplifting Trance" }, { "name": "Urdu" }, { "name": "Vaporwave" }, { "name": "Vocal Jazz" },
  { "name": "Vocal Trance" }, { "name": "Wave" }, { "name": "West Coast Hip Hop" }, { "name": "World Music" }, { "name": "Worship" }, { "name": "Zydeco" }
];